import XCTest
import SQLite3
@testable import SKLite

final class SqliteEnumTests: XCTestCase {
    func testConfig() {
        XCTAssertEqual(SKLite.Config.MULTITHREAD.rawValue, SQLITE_CONFIG_MULTITHREAD)
        XCTAssertEqual(SKLite.Config.SERIALIZED.rawValue, SQLITE_CONFIG_SERIALIZED)
        XCTAssertEqual(SKLite.Config.MALLOC.rawValue, SQLITE_CONFIG_MALLOC)
        XCTAssertEqual(SKLite.Config.GETMALLOC.rawValue, SQLITE_CONFIG_GETMALLOC)
        XCTAssertEqual(SKLite.Config.PAGECACHE.rawValue, SQLITE_CONFIG_PAGECACHE)
        XCTAssertEqual(SKLite.Config.HEAP.rawValue, SQLITE_CONFIG_HEAP)
        XCTAssertEqual(SKLite.Config.MEMSTATUS.rawValue, SQLITE_CONFIG_MEMSTATUS)
        XCTAssertEqual(SKLite.Config.MUTEX.rawValue, SQLITE_CONFIG_MUTEX)
        XCTAssertEqual(SKLite.Config.GETMUTEX.rawValue, SQLITE_CONFIG_GETMUTEX)
        XCTAssertEqual(SKLite.Config.LOOKASIDE.rawValue, SQLITE_CONFIG_LOOKASIDE)
        XCTAssertEqual(SKLite.Config.URI.rawValue, SQLITE_CONFIG_URI)
        XCTAssertEqual(SKLite.Config.PCACHE2.rawValue, SQLITE_CONFIG_PCACHE2)
        XCTAssertEqual(SKLite.Config.GETPCACHE2.rawValue, SQLITE_CONFIG_GETPCACHE2)
        XCTAssertEqual(SKLite.Config.COVERING_INDEX_SCAN.rawValue, SQLITE_CONFIG_COVERING_INDEX_SCAN)
        XCTAssertEqual(SKLite.Config.SQLLOG.rawValue, SQLITE_CONFIG_SQLLOG)
        XCTAssertEqual(SKLite.Config.MMAP_SIZE.rawValue, SQLITE_CONFIG_MMAP_SIZE)
        XCTAssertEqual(SKLite.Config.WIN32_HEAPSIZE.rawValue, SQLITE_CONFIG_WIN32_HEAPSIZE)
        XCTAssertEqual(SKLite.Config.PCACHE_HDRSZ.rawValue, SQLITE_CONFIG_PCACHE_HDRSZ)
        XCTAssertEqual(SKLite.Config.STMTJRNL_SPILL.rawValue, SQLITE_CONFIG_STMTJRNL_SPILL)
        XCTAssertEqual(SKLite.Config.SMALL_MALLOC.rawValue, SQLITE_CONFIG_SMALL_MALLOC)
        XCTAssertEqual(SKLite.Config.SORTERREF_SIZE.rawValue, SQLITE_CONFIG_SORTERREF_SIZE)
        XCTAssertEqual(SKLite.Config.MEMDB_MAXSIZE.rawValue, SQLITE_CONFIG_MEMDB_MAXSIZE)
    }
    
    func testDbConfig() {
        XCTAssertEqual(SKLite.DbConfig.MAIN_DB_NAME.rawValue, SQLITE_DBCONFIG_MAINDBNAME)
        XCTAssertEqual(SKLite.DbConfig.LOOKASIDE.rawValue, SQLITE_DBCONFIG_LOOKASIDE)
        XCTAssertEqual(SKLite.DbConfig.ENABLE_FKEY.rawValue, SQLITE_DBCONFIG_ENABLE_FKEY)
        XCTAssertEqual(SKLite.DbConfig.ENABLE_TRIGGER.rawValue, SQLITE_DBCONFIG_ENABLE_TRIGGER)
        XCTAssertEqual(SKLite.DbConfig.ENABLE_FTS3_TOKENIZER.rawValue, SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER)
        XCTAssertEqual(SKLite.DbConfig.ENABLE_LOAD_EXTENSION.rawValue, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION)
        XCTAssertEqual(SKLite.DbConfig.NO_CKPT_ON_CLOSE.rawValue, SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE)
        XCTAssertEqual(SKLite.DbConfig.ENABLE_QPSG.rawValue, SQLITE_DBCONFIG_ENABLE_QPSG)
        XCTAssertEqual(SKLite.DbConfig.TRIGGER_EQP.rawValue, SQLITE_DBCONFIG_TRIGGER_EQP)
        XCTAssertEqual(SKLite.DbConfig.RESET_DATABASE.rawValue, SQLITE_DBCONFIG_RESET_DATABASE)
        XCTAssertEqual(SKLite.DbConfig.DEFENSIVE.rawValue, SQLITE_DBCONFIG_DEFENSIVE)
        XCTAssertEqual(SKLite.DbConfig.WRITABLE_SCHEMA.rawValue, SQLITE_DBCONFIG_WRITABLE_SCHEMA)
    }
    
    func testSKLiteError() {
        // https://www.sqlite.org/rescode.html
        XCTAssertEqual(SKLite.SKLiteError.ABORT_ROLLBACK.rawValue, 516)
        XCTAssertEqual(SKLite.SKLiteError.AUTH_USER.rawValue, 279)
        XCTAssertEqual(SKLite.SKLiteError.BUSY_RECOVERY.rawValue, 261)
        XCTAssertEqual(SKLite.SKLiteError.BUSY_SNAPSHOT.rawValue, 517)
        XCTAssertEqual(SKLite.SKLiteError.BUSY_TIMEOUT.rawValue, 773)
        XCTAssertEqual(SKLite.SKLiteError.CANTOPEN_CONVPATH.rawValue, 1038)
        XCTAssertEqual(SKLite.SKLiteError.CANTOPEN_DIRTYWAL.rawValue, 1294)
        XCTAssertEqual(SKLite.SKLiteError.CANTOPEN_FULLPATH.rawValue, 782)
        XCTAssertEqual(SKLite.SKLiteError.CANTOPEN_ISDIR.rawValue, 526)
        XCTAssertEqual(SKLite.SKLiteError.CANTOPEN_NOTEMPDIR.rawValue, 270)
        XCTAssertEqual(SKLite.SKLiteError.CANTOPEN_SYMLINK.rawValue, 1550)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_CHECK.rawValue, 275)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_COMMITHOOK.rawValue, 531)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_DATATYPE.rawValue, 3091)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_FOREIGNKEY.rawValue, 787)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_FUNCTION.rawValue, 1043)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_NOTNULL.rawValue, 1299)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_PINNED.rawValue, 2835)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_PRIMARYKEY.rawValue, 1555)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_ROWID.rawValue, 2579)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_TRIGGER.rawValue, 1811)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_UNIQUE.rawValue, 2067)
        XCTAssertEqual(SKLite.SKLiteError.CONSTRAINT_VTAB.rawValue, 2323)
        XCTAssertEqual(SKLite.SKLiteError.CORRUPT_INDEX.rawValue, 779)
        XCTAssertEqual(SKLite.SKLiteError.CORRUPT_SEQUENCE.rawValue, 523)
        XCTAssertEqual(SKLite.SKLiteError.CORRUPT_VTAB.rawValue, 267)
        XCTAssertEqual(SKLite.SKLiteError.ERROR_MISSING_COLLSEQ.rawValue, 257)
        XCTAssertEqual(SKLite.SKLiteError.ERROR_RETRY.rawValue, 513)
        XCTAssertEqual(SKLite.SKLiteError.ERROR_SNAPSHOT.rawValue, 769)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_ACCESS.rawValue, 3338)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_AUTH.rawValue, 7178)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_BEGIN_ATOMIC.rawValue, 7434)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_BLOCKED.rawValue, 2826)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_CHECKRESERVEDLOCK.rawValue, 3594)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_CLOSE.rawValue, 4106)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_COMMIT_ATOMIC.rawValue, 7690)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_CONVPATH.rawValue, 6666)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_CORRUPTFS.rawValue, 8458)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_DATA.rawValue, 8202)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_DELETE.rawValue, 2570)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_DELETE_NOENT.rawValue, 5898)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_DIR_CLOSE.rawValue, 4362)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_DIR_FSYNC.rawValue, 1290)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_FSTAT.rawValue, 1802)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_FSYNC.rawValue, 1034)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_GETTEMPPATH.rawValue, 6410)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_LOCK.rawValue, 3850)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_MMAP.rawValue, 6154)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_NOMEM.rawValue, 3082)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_RDLOCK.rawValue, 2314)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_READ.rawValue, 266)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_ROLLBACK_ATOMIC.rawValue, 7946)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_SEEK.rawValue, 5642)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_SHMLOCK.rawValue, 5130)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_SHMMAP.rawValue, 5386)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_SHMOPEN.rawValue, 4618)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_SHMSIZE.rawValue, 4874)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_SHORT_READ.rawValue, 522)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_TRUNCATE.rawValue, 1546)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_UNLOCK.rawValue, 2058)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_VNODE.rawValue, 6922)
        XCTAssertEqual(SKLite.SKLiteError.IOERR_WRITE.rawValue, 778)
        XCTAssertEqual(SKLite.SKLiteError.LOCKED_SHAREDCACHE.rawValue, 262)
        XCTAssertEqual(SKLite.SKLiteError.LOCKED_VTAB.rawValue, 518)
        XCTAssertEqual(SKLite.SKLiteError.NOTICE_RECOVER_ROLLBACK.rawValue, 539)
        XCTAssertEqual(SKLite.SKLiteError.NOTICE_RECOVER_WAL.rawValue, 283)
        XCTAssertEqual(SKLite.SKLiteError.OK_LOAD_PERMANENTLY.rawValue, 256)
        XCTAssertEqual(SKLite.SKLiteError.READONLY_CANTINIT.rawValue, 1288)
        XCTAssertEqual(SKLite.SKLiteError.READONLY_CANTLOCK.rawValue, 520)
        XCTAssertEqual(SKLite.SKLiteError.READONLY_DBMOVED.rawValue, 1032)
        XCTAssertEqual(SKLite.SKLiteError.READONLY_DIRECTORY.rawValue, 1544)
        XCTAssertEqual(SKLite.SKLiteError.READONLY_RECOVERY.rawValue, 264)
        XCTAssertEqual(SKLite.SKLiteError.READONLY_ROLLBACK.rawValue, 776)
        XCTAssertEqual(SKLite.SKLiteError.WARNING_AUTOINDEX.rawValue, 284)
    }
    
    func testLimitFlag() {
        XCTAssertEqual(SKLite.Limit.LENGTH.rawValue, SQLITE_LIMIT_LENGTH)
        XCTAssertEqual(SKLite.Limit.SQL_LENGTH.rawValue, SQLITE_LIMIT_SQL_LENGTH)
        XCTAssertEqual(SKLite.Limit.COLUMN.rawValue, SQLITE_LIMIT_COLUMN)
        XCTAssertEqual(SKLite.Limit.EXPR_DEPTH.rawValue, SQLITE_LIMIT_EXPR_DEPTH)
        XCTAssertEqual(SKLite.Limit.COMPOUND_SELECT.rawValue, SQLITE_LIMIT_COMPOUND_SELECT)
        XCTAssertEqual(SKLite.Limit.VDBE_OP.rawValue, SQLITE_LIMIT_VDBE_OP)
        XCTAssertEqual(SKLite.Limit.FUNCTION_ARG.rawValue, SQLITE_LIMIT_FUNCTION_ARG)
        XCTAssertEqual(SKLite.Limit.ATTACHED.rawValue, SQLITE_LIMIT_ATTACHED)
        XCTAssertEqual(SKLite.Limit.LIKE_PATTERN_LENGTH.rawValue, SQLITE_LIMIT_LIKE_PATTERN_LENGTH)
        XCTAssertEqual(SKLite.Limit.VARIABLE_NUMBER.rawValue, SQLITE_LIMIT_VARIABLE_NUMBER)
        XCTAssertEqual(SKLite.Limit.TRIGGER_DEPTH.rawValue, SQLITE_LIMIT_TRIGGER_DEPTH)
        XCTAssertEqual(SKLite.Limit.WORKER_THREADS.rawValue, SQLITE_LIMIT_WORKER_THREADS)
    }
    
    func testColumnType() {
        XCTAssertEqual(SKLite.ColumnType.INTEGER.rawValue, SQLITE_INTEGER)
        XCTAssertEqual(SKLite.ColumnType.FLOAT.rawValue, SQLITE_FLOAT)
        XCTAssertEqual(SKLite.ColumnType.BLOB.rawValue, SQLITE_BLOB)
        XCTAssertEqual(SKLite.ColumnType.NULL.rawValue, SQLITE_NULL)
        XCTAssertEqual(SKLite.ColumnType.TEXT.rawValue, SQLITE_TEXT)
        XCTAssertEqual(SKLite.ColumnType.TEXT.rawValue, SQLITE3_TEXT)
    }
    
    func testTextEncoding() {
        XCTAssertEqual(SKLite.TextEncoding.UTF8.rawValue, SQLITE_UTF8)
        XCTAssertEqual(SKLite.TextEncoding.UTF16LE.rawValue, SQLITE_UTF16LE)
        XCTAssertEqual(SKLite.TextEncoding.UTF16BE.rawValue, SQLITE_UTF16BE)
        XCTAssertEqual(SKLite.TextEncoding.UTF16.rawValue, SQLITE_UTF16)
        XCTAssertEqual(SKLite.TextEncoding.ANY.rawValue, SQLITE_ANY)
        XCTAssertEqual(SKLite.TextEncoding.UTF16_ALIGNED.rawValue, SQLITE_UTF16_ALIGNED)
    }
    
    func testIndexConstraint() {
        XCTAssertEqual(SKLite.IndexConstraint.EQ.rawValue, SQLITE_INDEX_CONSTRAINT_EQ)
        XCTAssertEqual(SKLite.IndexConstraint.GT.rawValue, SQLITE_INDEX_CONSTRAINT_GT)
        XCTAssertEqual(SKLite.IndexConstraint.LE.rawValue, SQLITE_INDEX_CONSTRAINT_LE)
        XCTAssertEqual(SKLite.IndexConstraint.LT.rawValue, SQLITE_INDEX_CONSTRAINT_LT)
        XCTAssertEqual(SKLite.IndexConstraint.GE.rawValue, SQLITE_INDEX_CONSTRAINT_GE)
        XCTAssertEqual(SKLite.IndexConstraint.MATCH.rawValue, SQLITE_INDEX_CONSTRAINT_MATCH)
        XCTAssertEqual(SKLite.IndexConstraint.LIKE.rawValue, SQLITE_INDEX_CONSTRAINT_LIKE)
        XCTAssertEqual(SKLite.IndexConstraint.GLOB.rawValue, SQLITE_INDEX_CONSTRAINT_GLOB)
        XCTAssertEqual(SKLite.IndexConstraint.REGEXP.rawValue, SQLITE_INDEX_CONSTRAINT_REGEXP)
        XCTAssertEqual(SKLite.IndexConstraint.NE.rawValue, SQLITE_INDEX_CONSTRAINT_NE)
        XCTAssertEqual(SKLite.IndexConstraint.ISNOT.rawValue, SQLITE_INDEX_CONSTRAINT_ISNOT)
        XCTAssertEqual(SKLite.IndexConstraint.ISNOTNULL.rawValue, SQLITE_INDEX_CONSTRAINT_ISNOTNULL)
        XCTAssertEqual(SKLite.IndexConstraint.ISNULL.rawValue, SQLITE_INDEX_CONSTRAINT_ISNULL)
        XCTAssertEqual(SKLite.IndexConstraint.IS.rawValue, SQLITE_INDEX_CONSTRAINT_IS)
        XCTAssertEqual(SKLite.IndexConstraint.FUNCTION.rawValue, SQLITE_INDEX_CONSTRAINT_FUNCTION)
    }
    
    func testDbStatus() {
        XCTAssertEqual(SKLite.DbStatus.LOOKASIDE_USED.rawValue, SQLITE_DBSTATUS_LOOKASIDE_USED)
        XCTAssertEqual(SKLite.DbStatus.CACHE_USED.rawValue, SQLITE_DBSTATUS_CACHE_USED)
        XCTAssertEqual(SKLite.DbStatus.SCHEMA_USED.rawValue, SQLITE_DBSTATUS_SCHEMA_USED)
        XCTAssertEqual(SKLite.DbStatus.STMT_USED.rawValue, SQLITE_DBSTATUS_STMT_USED)
        XCTAssertEqual(SKLite.DbStatus.LOOKASIDE_HIT.rawValue, SQLITE_DBSTATUS_LOOKASIDE_HIT)
        XCTAssertEqual(SKLite.DbStatus.LOOKASIDE_MISS_SIZE.rawValue, SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE)
        XCTAssertEqual(SKLite.DbStatus.LOOKASIDE_MISS_FULL.rawValue, SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL)
        XCTAssertEqual(SKLite.DbStatus.CACHE_HIT.rawValue, SQLITE_DBSTATUS_CACHE_HIT)
        XCTAssertEqual(SKLite.DbStatus.CACHE_MISS.rawValue, SQLITE_DBSTATUS_CACHE_MISS)
        XCTAssertEqual(SKLite.DbStatus.CACHE_WRITE.rawValue, SQLITE_DBSTATUS_CACHE_WRITE)
        XCTAssertEqual(SKLite.DbStatus.DEFERRED_FKS.rawValue, SQLITE_DBSTATUS_DEFERRED_FKS)
        XCTAssertEqual(SKLite.DbStatus.CACHE_USED_SHARED.rawValue, SQLITE_DBSTATUS_CACHE_USED_SHARED)
        XCTAssertEqual(SKLite.DbStatus.CACHE_SPILL.rawValue, SQLITE_DBSTATUS_CACHE_SPILL)
        XCTAssertEqual(SKLite.DbStatus.MAX, SQLITE_DBSTATUS_MAX)
    }
    
    func testStatus() {
        XCTAssertEqual(SKLite.Status.MEMORY_USED.rawValue, SQLITE_STATUS_MEMORY_USED)
        XCTAssertEqual(SKLite.Status.PAGECACHE_USED.rawValue, SQLITE_STATUS_PAGECACHE_USED)
        XCTAssertEqual(SKLite.Status.PAGECACHE_OVERFLOW.rawValue, SQLITE_STATUS_PAGECACHE_OVERFLOW)
        XCTAssertEqual(SKLite.Status.SCRATCH_USED.rawValue, SQLITE_STATUS_SCRATCH_USED)
        XCTAssertEqual(SKLite.Status.SCRATCH_OVERFLOW.rawValue, SQLITE_STATUS_SCRATCH_OVERFLOW)
        XCTAssertEqual(SKLite.Status.MALLOC_SIZE.rawValue, SQLITE_STATUS_MALLOC_SIZE)
        XCTAssertEqual(SKLite.Status.PARSER_STACK.rawValue, SQLITE_STATUS_PARSER_STACK)
        XCTAssertEqual(SKLite.Status.PAGECACHE_SIZE.rawValue, SQLITE_STATUS_PAGECACHE_SIZE)
        XCTAssertEqual(SKLite.Status.SCRATCH_SIZE.rawValue, SQLITE_STATUS_SCRATCH_SIZE)
        XCTAssertEqual(SKLite.Status.MALLOC_COUNT.rawValue, SQLITE_STATUS_MALLOC_COUNT)
    }
    
    func testStmtStatus() {
        XCTAssertEqual(SKLite.StmtStatus.FULLSCAN_STEP.rawValue, SQLITE_STMTSTATUS_FULLSCAN_STEP)
        XCTAssertEqual(SKLite.StmtStatus.SORT.rawValue, SQLITE_STMTSTATUS_SORT)
        XCTAssertEqual(SKLite.StmtStatus.AUTOINDEX.rawValue, SQLITE_STMTSTATUS_AUTOINDEX)
        XCTAssertEqual(SKLite.StmtStatus.VM_STEP.rawValue, SQLITE_STMTSTATUS_VM_STEP)
        XCTAssertEqual(SKLite.StmtStatus.REPREPARE.rawValue, SQLITE_STMTSTATUS_REPREPARE)
        XCTAssertEqual(SKLite.StmtStatus.RUN.rawValue, SQLITE_STMTSTATUS_RUN)
        XCTAssertEqual(SKLite.StmtStatus.MEMUSED.rawValue, SQLITE_STMTSTATUS_MEMUSED)
    }
    
    func testConfilict() {
        XCTAssertEqual(SKLite.Conflict.ROLLBACK.rawValue, SQLITE_ROLLBACK)
        XCTAssertEqual(SKLite.Conflict.ABORT.rawValue, SQLITE_ABORT)
        XCTAssertEqual(SKLite.Conflict.FAIL.rawValue, SQLITE_FAIL)
        XCTAssertEqual(SKLite.Conflict.IGNORE.rawValue, SQLITE_IGNORE)
        XCTAssertEqual(SKLite.Conflict.REPLACE.rawValue, SQLITE_REPLACE)
    }
}
